---
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
  - repo: https://github.com/chriskuehl/puppet-pre-commit-hooks.git
    rev: v2.2.0
    hooks:
      - id: bolt-validate
      - id: epp-validate
      - id: erb-validate
      - id: puppet-lint
        args:
          - --fail-on-warnings
      - id: puppet-validate
      - id: r10k-validate
      - id: ruby-validate
